---
kind: pipeline
type: docker
name: notify

# clone:
#   disable: true

steps:
- name: notify
  image: docker
  commands:
    - echo "notify"
trigger:
  branch:
  - master
  
---
kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build